name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    if: github.repository_owner == 'dihm'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Linting
        uses: astral-sh/ruff-action@v3
        with:
          src: "./src"
